name: Build_nginxwebui

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:
    inputs:
      clean_cache:
        description: 'Clear caches'
        required: false
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{secrets.REPOSITORY}}
          ref: main
          token: ${{ secrets.DUBUXTOKEN }}
          submodules: true
          show-progress: true

      - name: modify
        run: |
          cd nginxWebUI_Modify
          sh copy.sh        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: build_JAR_AND_Images
        id: build_JAR_AND_Images
        run : |
          mkdir -p nginxWebUI/src/main/resources/acme
          unzip -d nginxWebUI/src/main/resources/acme nginxWebUI/src/main/resources/acme.zip
          cd nginxWebUI
          mv -f synology_dsm_local.sh ../nginxWebUI/src/main/resources/acme/
          zip -r acme.zip -s 0 ../nginxWebUI/src/main/resources/acme/*
          rm -rf ../nginxWebUI/src/main/resources/acme
          mv -f acme.zip ../nginxWebUI/src/main/resources/
          mvn clean package
          docker build -t nginxwebui:latest .
          
      - name: Login to aliyuncs
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.HUB_NAME }}
          password: ${{ secrets.HUB_PASS }}

      # Runs a single command using the runners shell
      - name: Push Docker images
        id : Push_Docker_Images
        run : |
           imageName=nginxwebui
           docker tag $imageName registry.cn-hangzhou.aliyuncs.com/dubux/$imageName:latest
           docker push registry.cn-hangzhou.aliyuncs.com/dubux/$imageName
      - name: Check Synology SPK    
        uses: actions/checkout@v4
        with:
          repository: ${{secrets.SYNOLOGYSPK}}
          ref: main
          token: ${{ secrets.DUBUXTOKEN }}
          submodules: true
          show-progress: true    
      - name: Build SPK
        id: Build_SPK
        run : |
          dir="nginxwebui"
          isExist='false'
          if [ -d "$dir" ]; then  
              cd $dir && pwd && chmod +x ./pkgCreate.sh && ./pkgCreate.sh
              isExist='true'
          fi
          echo "isExist=${isExist}" >> $GITHUB_ENV
          
      
      - name: Release
        uses: ncipollo/release-action@v1
        id: release_packages
        if: env.isExist == 'true'
        with:
            artifacts: "${{ github.workspace }}/nginxwebui/build/*.spk"
            allowUpdates: true
            token: ${{ secrets.DUBUXTOKEN }}
            generateReleaseNotes: false
            tag: "v1.0.0"
            body: |
                ${{ github.event.head_commit.message }}
                ${{steps.desc.outputs.release}}
            replacesArtifacts: true