name: Build_shenzhuo

on:
  schedule:
    - cron: '0 18 * * 0,2,4,6'
  workflow_dispatch:
    inputs:
      clean_cache:
        description: 'Clear caches'
        required: false
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{secrets.REPOSITORY}}
          ref: main
          token: ${{ secrets.DUBUXTOKEN }}
          submodules: true
          show-progress: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: build_JAR_AND_Images
        id: build_JAR_AND_Images
        run : |
          cd shenzhuo
          mkdir ./shenzhuo_install
          cd shenzhuo_install
          SHENZHUO_VERSION=9.3.8.2
          curl -Lo shenzhuo.tar "https://download.shenzhuohl.com/down/chuantou/ubuntu/${SHENZHUO_VERSION}/shenzhuo.tar"
          tar -xf shenzhuo.tar && rm -rf shenzhuo.tar
          mv * ../shenzhuo/rootfs/etc/s6-overlay/s6-rc.d/shenzhuo/
          docker build -t shenzhuo:latest .
          
      - name: Login to aliyuncs
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.HUB_NAME }}
          password: ${{ secrets.HUB_PASS }}

      # Runs a single command using the runners shell
      - name: Push Docker images
        id : Push_Docker_Images
        run : |
           imageName=shenzhuo
           docker tag $imageName registry.cn-hangzhou.aliyuncs.com/dubux/$imageName:latest
           docker push registry.cn-hangzhou.aliyuncs.com/dubux/$imageName
