name: Build_unas

on:
  schedule:
    - cron: '0 18 * * 0,2,4,6'
  workflow_dispatch:
    inputs:
      clean_cache:
        description: 'Clear caches'
        required: false
        type: boolean

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{secrets.REPOSITORY}}
          ref: main
          token: ${{ secrets.DUBUXTOKEN }}
          submodules: true
          show-progress: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: build_JAR_AND_Images
        id: build_JAR_AND_Images
        run : |
          cd unas
          docker build -t unas:latest .
          
      - name: Login to aliyuncs
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.HUB_NAME }}
          password: ${{ secrets.HUB_PASS }}

      # Runs a single command using the runners shell
      - name: Push Docker images
        id : Push_Docker_Images
        run : |
           imageName=unas
           docker tag $imageName registry.cn-hangzhou.aliyuncs.com/dubux/$imageName:latest
           docker push registry.cn-hangzhou.aliyuncs.com/dubux/$imageName

      - name: Check Synology SPK    
        uses: actions/checkout@v4
        with:
          repository: ${{secrets.SYNOLOGYSPK}}
          ref: main
          token: ${{ secrets.DUBUXTOKEN }}
          submodules: true
          show-progress: true    
      - name: Build SPK
        id: Build_SPK
        run : |
          dir="unas"
          isExist='false'
          if [ -d "$dir" ]; then  
              cd $dir && pwd && chmod +x ./pkgCreate.sh && ./pkgCreate.sh
              isExist='true'
          fi
          echo "isExist=${isExist}" >> $GITHUB_ENV
          
      
      - name: Release
        uses: ncipollo/release-action@v1
        id: release_packages
        if: env.isExist == 'true'
        with:
            artifacts: "${{ github.workspace }}/unas/build/*.spk"
            allowUpdates: true
            token: ${{ secrets.DUBUXTOKEN }}
            generateReleaseNotes: false
            tag: "v1.0.0"
            body: |
                ${{ github.event.head_commit.message }}
                ${{steps.desc.outputs.release}}
            replacesArtifacts: true