name: 'submodule-v2ray-plugin-android'

on:
  schedule:
  - cron: "0 2 * * *"
  workflow_dispatch:
    inputs:
      clean_cache:
        description: 'Clear caches'
        required: false
        type: boolean

jobs:
  sync:
    name: 'Submodules Sync'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: ${{secrets.REPOSITORY2}}
        ref: main
        token: ${{ secrets.DUBUXTOKEN }}
        submodules: true
        show-progress: true

    - name: Git Sumbodule Update
      run: |
        git pull --recurse-submodules
        git submodule update --remote --recursive

    - name: Commit update
      run: |
        git config --global user.name 'Action Bot'
        git config --global user.email 'bot@noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.DUBUXTOKEN }}@github.com/${{secrets.REPOSITORY2}}
        git commit -am "Auto updated submodule references" && git push || echo "No changes to commit"
